name: Deploy via Bastion Host

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/melbourne-cooling-solution .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/melbourne-cooling-solution

    - name: Write EC2 private key
      run: echo "${{ secrets.EC2_KEY }}" > ec2_key.pem && chmod 600 ec2_key.pem

    - name: Deploy to EC2 via Bastion
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.BASTION_HOST }}
        username: ${{ secrets.BASTION_USER }}
        key: ${{ secrets.BASTION_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/melbourne-cooling-solution
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/melbourne-cooling-solution
          EOF
